log_wave /video_terminal_tb/DUT/char_rate
log_wave /video_terminal_tb/DUT/dot_rate
log_wave /video_terminal_tb/DUT/units
log_wave /video_terminal_tb/DUT/tens
log_wave /video_terminal_tb/DUT/v
log_wave /video_terminal_tb/DUT/hbl_n
log_wave /video_terminal_tb/DUT/h_sync_n
log_wave /video_terminal_tb/DUT/line_phi
log_wave /video_terminal_tb/DUT/mem_phi
log_wave /video_terminal_tb/DUT/vinh_n
log_wave /video_terminal_tb/DUT/line_7
log_wave /video_terminal_tb/DUT/vbl_n
log_wave /video_terminal_tb/DUT/pix_ld_n
log_wave /video_terminal_tb/DUT/d15/pe_n
log_wave /video_terminal_tb/DUT/d15/q
log_wave /video_terminal_tb/DUT/vid1
log_wave /video_terminal_tb/DUT/vid2
log_wave /video_terminal_tb/DUT/clr_btn
log_wave /video_terminal_tb/DUT/wc1_n
log_wave /video_terminal_tb/DUT/wc2_n
log_wave /video_terminal_tb/DUT/last
log_wave /video_terminal_tb/DUT/last_h
log_wave /video_terminal_tb/DUT/curs
log_wave /video_terminal_tb/DUT/write_n
log_wave /video_terminal_tb/DUT/rd
log_wave /video_terminal_tb/DUT/da
log_wave /video_terminal_tb/DUT/rda_n
log_wave /video_terminal_tb/DUT/d2/x
log_wave /video_terminal_tb/DUT/cb
log_wave /video_terminal_tb/DUT/co
run all
exit
