log_wave /video_terminal_tb/char_rate
log_wave /video_terminal_tb/dot_rate
log_wave /video_terminal_tb/units
log_wave /video_terminal_tb/tens
log_wave /video_terminal_tb/v
log_wave /video_terminal_tb/hbl_n
log_wave /video_terminal_tb/h_sync_n
log_wave /video_terminal_tb/line_phi
log_wave /video_terminal_tb/mem_phi
log_wave /video_terminal_tb/vinh_n
log_wave /video_terminal_tb/line_7
log_wave /video_terminal_tb/vbl_n
log_wave /video_terminal_tb/pix_ld_n
log_wave /video_terminal_tb/d15/pe_n
log_wave /video_terminal_tb/d15/q
log_wave /video_terminal_tb/vid1
log_wave /video_terminal_tb/vid2
log_wave /video_terminal_tb/clr_btn
log_wave /video_terminal_tb/wc1_n
log_wave /video_terminal_tb/wc2_n
log_wave /video_terminal_tb/last
log_wave /video_terminal_tb/last_h
log_wave /video_terminal_tb/curs
log_wave /video_terminal_tb/write_n
log_wave /video_terminal_tb/rd
log_wave /video_terminal_tb/da
log_wave /video_terminal_tb/rda_n
log_wave /video_terminal_tb/d2/x
log_wave /video_terminal_tb/cb
log_wave /video_terminal_tb/co
run all
exit
